# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\NXP\2018NXP\2侯宇轩工具\PyQt5-SerialPort-smartcar\GUI\SerialPort.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1072, 579)
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Form.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon_128.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("/*color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 25, 25);\n"
"font: 9pt \"方正兰亭中黑_GBK\";*/")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_msg = QtWidgets.QWidget()
        self.tab_msg.setObjectName("tab_msg")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_msg)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab_msg)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.hexShowing_checkBox = QtWidgets.QCheckBox(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hexShowing_checkBox.sizePolicy().hasHeightForWidth())
        self.hexShowing_checkBox.setSizePolicy(sizePolicy)
        self.hexShowing_checkBox.setObjectName("hexShowing_checkBox")
        self.horizontalLayout_2.addWidget(self.hexShowing_checkBox)
        self.ClearButton = QtWidgets.QPushButton(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearButton.sizePolicy().hasHeightForWidth())
        self.ClearButton.setSizePolicy(sizePolicy)
        self.ClearButton.setObjectName("ClearButton")
        self.horizontalLayout_2.addWidget(self.ClearButton)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.textEdit_Recive = QtWidgets.QTextEdit(self.tab_msg)
        self.textEdit_Recive.setStyleSheet("/*background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);*/")
        self.textEdit_Recive.setObjectName("textEdit_Recive")
        self.gridLayout_3.addWidget(self.textEdit_Recive, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.hexSending_checkBox = QtWidgets.QCheckBox(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hexSending_checkBox.sizePolicy().hasHeightForWidth())
        self.hexSending_checkBox.setSizePolicy(sizePolicy)
        self.hexSending_checkBox.setObjectName("hexSending_checkBox")
        self.horizontalLayout.addWidget(self.hexSending_checkBox)
        self.Send_Button = QtWidgets.QPushButton(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_Button.sizePolicy().hasHeightForWidth())
        self.Send_Button.setSizePolicy(sizePolicy)
        self.Send_Button.setObjectName("Send_Button")
        self.horizontalLayout.addWidget(self.Send_Button)
        self.pushButton_clearSendText = QtWidgets.QPushButton(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clearSendText.sizePolicy().hasHeightForWidth())
        self.pushButton_clearSendText.setSizePolicy(sizePolicy)
        self.pushButton_clearSendText.setObjectName("pushButton_clearSendText")
        self.horizontalLayout.addWidget(self.pushButton_clearSendText)
        self.gridLayout_3.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.textEdit_Send = QtWidgets.QTextEdit(self.tab_msg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_Send.sizePolicy().hasHeightForWidth())
        self.textEdit_Send.setSizePolicy(sizePolicy)
        self.textEdit_Send.setStyleSheet("/*background-color: rgb(0, 0, 0);*/")
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.gridLayout_3.addWidget(self.textEdit_Send, 3, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_msg, "")
        self.tab_img = QtWidgets.QWidget()
        self.tab_img.setObjectName("tab_img")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_img)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_width = QtWidgets.QLineEdit(self.tab_img)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_width.sizePolicy().hasHeightForWidth())
        self.lineEdit_width.setSizePolicy(sizePolicy)
        self.lineEdit_width.setInputMask("")
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.gridLayout_2.addWidget(self.lineEdit_width, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_img)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_height = QtWidgets.QLineEdit(self.tab_img)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_height.sizePolicy().hasHeightForWidth())
        self.lineEdit_height.setSizePolicy(sizePolicy)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.gridLayout_2.addWidget(self.lineEdit_height, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.tab_img)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.comboBox_imgType = QtWidgets.QComboBox(self.tab_img)
        self.comboBox_imgType.setObjectName("comboBox_imgType")
        self.comboBox_imgType.addItem("")
        self.comboBox_imgType.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_imgType, 0, 1, 1, 1)
        self.checkBox_UseOpenCV = QtWidgets.QCheckBox(self.tab_img)
        self.checkBox_UseOpenCV.setObjectName("checkBox_UseOpenCV")
        self.gridLayout_2.addWidget(self.checkBox_UseOpenCV, 0, 6, 1, 1)
        self.label_img = WidgetPainter(self.tab_img)
        self.label_img.setMouseTracking(True)
        self.label_img.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_img.setObjectName("label_img")
        self.gridLayout_2.addWidget(self.label_img, 3, 1, 1, 6)
        self.pushButton_saveImg = QtWidgets.QPushButton(self.tab_img)
        self.pushButton_saveImg.setObjectName("pushButton_saveImg")
        self.gridLayout_2.addWidget(self.pushButton_saveImg, 2, 1, 1, 1)
        self.label_position = QtWidgets.QLabel(self.tab_img)
        self.label_position.setObjectName("label_position")
        self.gridLayout_2.addWidget(self.label_position, 2, 6, 1, 1)
        self.checkBox_showGrid = QtWidgets.QCheckBox(self.tab_img)
        self.checkBox_showGrid.setObjectName("checkBox_showGrid")
        self.gridLayout_2.addWidget(self.checkBox_showGrid, 1, 6, 1, 1)
        self.label_pause = QtWidgets.QLabel(self.tab_img)
        self.label_pause.setText("")
        self.label_pause.setObjectName("label_pause")
        self.gridLayout_2.addWidget(self.label_pause, 2, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(269, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 4, 1, 2)
        self.tabWidget.addTab(self.tab_img, "")
        self.tab_parameter = QtWidgets.QWidget()
        self.tab_parameter.setObjectName("tab_parameter")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_parameter)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_parameter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.listWidget_para = QtWidgets.QListWidget(self.tab_parameter)
        self.listWidget_para.setObjectName("listWidget_para")
        self.gridLayout_4.addWidget(self.listWidget_para, 1, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(564, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        self.pushButton_readMCU = QtWidgets.QPushButton(self.tab_parameter)
        self.pushButton_readMCU.setObjectName("pushButton_readMCU")
        self.gridLayout_4.addWidget(self.pushButton_readMCU, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_parameter, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.gridLayout_portInform = QtWidgets.QGridLayout()
        self.gridLayout_portInform.setObjectName("gridLayout_portInform")
        self.Time_Label = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Time_Label.sizePolicy().hasHeightForWidth())
        self.Time_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Time_Label.setFont(font)
        self.Time_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Time_Label.setObjectName("Time_Label")
        self.gridLayout_portInform.addWidget(self.Time_Label, 17, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_portInform.addItem(spacerItem3, 15, 0, 1, 1)
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setStyleSheet("/*alternate-background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);*/")
        self.calendarWidget.setFirstDayOfWeek(QtCore.Qt.Sunday)
        self.calendarWidget.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout_portInform.addWidget(self.calendarWidget, 18, 1, 1, 1)
        self.About_Button = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("方正兰亭中黑_GBK")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.About_Button.setFont(font)
        self.About_Button.setObjectName("About_Button")
        self.gridLayout_portInform.addWidget(self.About_Button, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_portInform.addWidget(self.line_2, 0, 0, 19, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_parity = QtWidgets.QComboBox(Form)
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.comboBox_parity.addItem("")
        self.gridLayout.addWidget(self.comboBox_parity, 4, 1, 1, 1)
        self.Com_Baud_Combo = QtWidgets.QComboBox(Form)
        self.Com_Baud_Combo.setEditable(True)
        self.Com_Baud_Combo.setDuplicatesEnabled(False)
        self.Com_Baud_Combo.setModelColumn(0)
        self.Com_Baud_Combo.setObjectName("Com_Baud_Combo")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.Com_Baud_Combo.addItem("")
        self.gridLayout.addWidget(self.Com_Baud_Combo, 3, 1, 1, 1)
        self.Com_Refresh_Button = QtWidgets.QPushButton(Form)
        self.Com_Refresh_Button.setObjectName("Com_Refresh_Button")
        self.gridLayout.addWidget(self.Com_Refresh_Button, 0, 1, 1, 1)
        self.Com_Name_Combo = QtWidgets.QComboBox(Form)
        self.Com_Name_Combo.setObjectName("Com_Name_Combo")
        self.gridLayout.addWidget(self.Com_Name_Combo, 2, 1, 1, 1)
        self.Com_Close_Button = QtWidgets.QPushButton(Form)
        self.Com_Close_Button.setDefault(False)
        self.Com_Close_Button.setObjectName("Com_Close_Button")
        self.gridLayout.addWidget(self.Com_Close_Button, 9, 1, 1, 1)
        self.Com_Baud_Label = QtWidgets.QLabel(Form)
        self.Com_Baud_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Baud_Label.setObjectName("Com_Baud_Label")
        self.gridLayout.addWidget(self.Com_Baud_Label, 3, 0, 1, 1)
        self.Com_Name_Label = QtWidgets.QLabel(Form)
        self.Com_Name_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Name_Label.setObjectName("Com_Name_Label")
        self.gridLayout.addWidget(self.Com_Name_Label, 2, 0, 1, 1)
        self.Com_Refresh_Label = QtWidgets.QLabel(Form)
        self.Com_Refresh_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_Refresh_Label.setObjectName("Com_Refresh_Label")
        self.gridLayout.addWidget(self.Com_Refresh_Label, 0, 0, 1, 1)
        self.comboBox_data = QtWidgets.QComboBox(Form)
        self.comboBox_data.setObjectName("comboBox_data")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.comboBox_data.addItem("")
        self.gridLayout.addWidget(self.comboBox_data, 5, 1, 1, 1)
        self.Com_Open_Button = QtWidgets.QPushButton(Form)
        self.Com_Open_Button.setObjectName("Com_Open_Button")
        self.gridLayout.addWidget(self.Com_Open_Button, 7, 1, 1, 1)
        self.Com_isOpenOrNot_Label = QtWidgets.QLabel(Form)
        self.Com_isOpenOrNot_Label.setText("")
        self.Com_isOpenOrNot_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_isOpenOrNot_Label.setObjectName("Com_isOpenOrNot_Label")
        self.gridLayout.addWidget(self.Com_isOpenOrNot_Label, 9, 0, 1, 1)
        self.Com_State_Label = QtWidgets.QLabel(Form)
        self.Com_State_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Com_State_Label.setObjectName("Com_State_Label")
        self.gridLayout.addWidget(self.Com_State_Label, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.comboBox_stop = QtWidgets.QComboBox(Form)
        self.comboBox_stop.setObjectName("comboBox_stop")
        self.comboBox_stop.addItem("")
        self.comboBox_stop.addItem("")
        self.gridLayout.addWidget(self.comboBox_stop, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.gridLayout_portInform.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_portInform)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        self.Com_Baud_Combo.setCurrentIndex(10)
        self.comboBox_data.setCurrentIndex(3)
        self.comboBox_stop.setCurrentIndex(0)
        self.ClearButton.clicked.connect(self.textEdit_Recive.clear)
        self.pushButton_clearSendText.clicked.connect(self.textEdit_Send.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PyQt智能车调试助手"))
        self.label.setText(_translate("Form", "接收区"))
        self.hexShowing_checkBox.setText(_translate("Form", "16进制显示"))
        self.ClearButton.setText(_translate("Form", "清除"))
        self.textEdit_Recive.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("Form", "发送区"))
        self.hexSending_checkBox.setText(_translate("Form", "16进制发送"))
        self.Send_Button.setText(_translate("Form", "发送"))
        self.pushButton_clearSendText.setText(_translate("Form", "清除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_msg), _translate("Form", "接收发送数据"))
        self.lineEdit_width.setText(_translate("Form", "80"))
        self.label_5.setText(_translate("Form", "高"))
        self.lineEdit_height.setText(_translate("Form", "60"))
        self.label_6.setText(_translate("Form", "宽"))
        self.comboBox_imgType.setItemText(0, _translate("Form", "二值化图像"))
        self.comboBox_imgType.setItemText(1, _translate("Form", "灰度图像(单片机解压)"))
        self.checkBox_UseOpenCV.setText(_translate("Form", "使用OpenCV查看图像"))
        self.pushButton_saveImg.setText(_translate("Form", "保存图像"))
        self.label_position.setText(_translate("Form", "鼠标位置 x:  0,y:  0"))
        self.checkBox_showGrid.setText(_translate("Form", "显示网格线"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_img), _translate("Form", "查看图像"))
        self.label_4.setText(_translate("Form", "参数"))
        self.pushButton_readMCU.setText(_translate("Form", "更新上位机数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_parameter), _translate("Form", "调节参数"))
        self.Time_Label.setText(_translate("Form", "Time"))
        self.About_Button.setText(_translate("Form", "Made by PyQt5 - 查看源代码"))
        self.comboBox_parity.setItemText(0, _translate("Form", "无校验"))
        self.comboBox_parity.setItemText(1, _translate("Form", "偶校验"))
        self.comboBox_parity.setItemText(2, _translate("Form", "奇校验"))
        self.comboBox_parity.setItemText(3, _translate("Form", "空校验"))
        self.comboBox_parity.setItemText(4, _translate("Form", "标志校验"))
        self.Com_Baud_Combo.setCurrentText(_translate("Form", "115200"))
        self.Com_Baud_Combo.setItemText(0, _translate("Form", "1200"))
        self.Com_Baud_Combo.setItemText(1, _translate("Form", "2400"))
        self.Com_Baud_Combo.setItemText(2, _translate("Form", "4800"))
        self.Com_Baud_Combo.setItemText(3, _translate("Form", "9600"))
        self.Com_Baud_Combo.setItemText(4, _translate("Form", "14400"))
        self.Com_Baud_Combo.setItemText(5, _translate("Form", "19200"))
        self.Com_Baud_Combo.setItemText(6, _translate("Form", "38400"))
        self.Com_Baud_Combo.setItemText(7, _translate("Form", "43000"))
        self.Com_Baud_Combo.setItemText(8, _translate("Form", "57600"))
        self.Com_Baud_Combo.setItemText(9, _translate("Form", "76800"))
        self.Com_Baud_Combo.setItemText(10, _translate("Form", "115200"))
        self.Com_Baud_Combo.setItemText(11, _translate("Form", "128000"))
        self.Com_Baud_Combo.setItemText(12, _translate("Form", "230400"))
        self.Com_Baud_Combo.setItemText(13, _translate("Form", "256000"))
        self.Com_Baud_Combo.setItemText(14, _translate("Form", "460800"))
        self.Com_Baud_Combo.setItemText(15, _translate("Form", "921600"))
        self.Com_Baud_Combo.setItemText(16, _translate("Form", "1382400"))
        self.Com_Refresh_Button.setText(_translate("Form", "刷新"))
        self.Com_Close_Button.setText(_translate("Form", "Close"))
        self.Com_Baud_Label.setText(_translate("Form", "波特率"))
        self.Com_Name_Label.setText(_translate("Form", "串口选择"))
        self.Com_Refresh_Label.setText(_translate("Form", "串口搜索"))
        self.comboBox_data.setItemText(0, _translate("Form", "5"))
        self.comboBox_data.setItemText(1, _translate("Form", "6"))
        self.comboBox_data.setItemText(2, _translate("Form", "7"))
        self.comboBox_data.setItemText(3, _translate("Form", "8"))
        self.Com_Open_Button.setText(_translate("Form", "Open"))
        self.Com_State_Label.setText(_translate("Form", "串口操作"))
        self.label_3.setText(_translate("Form", "奇偶位"))
        self.comboBox_stop.setItemText(0, _translate("Form", "1"))
        self.comboBox_stop.setItemText(1, _translate("Form", "2"))
        self.label_7.setText(_translate("Form", "数据位"))
        self.label_8.setText(_translate("Form", "停止位"))

from widgetpainter import WidgetPainter
import res_rc
